# GitHub Actions pour déploiement Azure App Service Python
name: Build and deploy Python app to Azure Web App - GestionAbsences

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  WEBSITE_HOSTNAME: gestionabsences.azurewebsites.net
  AZURE_POSTGRESQL_CONNECTIONSTRING: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}
  AZURE_DATABASE_URL: ${{ secrets.AZURE_DATABASE_URL }}
  DJANGO_SETTINGS_MODULE: gestion_absencesApp.settings

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies
        run: ./venv/bin/pip install -r requirements.txt

      - name: Collect static files
        env:
          DJANGO_SETTINGS_MODULE: gestion_absencesApp.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          AZURE_POSTGRESQL_CONNECTIONSTRING: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}
        run: ./venv/bin/python manage.py collectstatic --noinput

      - name: Migrate database
        env:
          DJANGO_SETTINGS_MODULE: gestion_absencesApp.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          AZURE_DATABASE_URL: ${{ secrets.AZURE_DATABASE_URL }}
          AZURE_POSTGRESQL_CONNECTIONSTRING: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}
        run: ./venv/bin/python manage.py migrate --noinput

      - name: Debug DNS et string
        run: |
          echo "DNS resolution test"
          ping -c 3 gestionbsencesapp-server.postgres.database.azure.com || echo "DNS échec"
          echo "Connexion DB = $AZURE_POSTGRESQL_CONNECTIONSTRING"

      - name: Debug AZURE_DATABASE_URL
        run: echo "AZURE_DATABASE_URL=$AZURE_DATABASE_URL"

      - name: Créer superuser si inexistant
        env:
          DJANGO_SETTINGS_MODULE: gestion_absencesApp.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          AZURE_POSTGRESQL_CONNECTIONSTRING: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}
        run: ./venv/bin/python manage.py create_superuser

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'GestionAbsences'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D340EA17717F43B68438F84A41C38B2E }}
